apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    cluster: teric-uat
    region: asia-northeast1-b	
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
